Repository Avaiga/taipy-gui, pull requests merged in 2022-10, with the labels that each got.

#437 Update doc
  src/taipy/gui/__init__.py
  src/taipy/gui/gui.py
Labels: Documentation

#438 Complement Reference Manual.
  src/taipy/gui/gui.py
Labels: Documentation

#446 Regression linked to Gantt like chart (#445)
  gui/src/components/Taipy/Chart.tsx
Labels: Bug, Front-End

#444 Long running tasks (#442)
  src/taipy/gui/__init__.py
  src/taipy/gui/gui.py
  src/taipy/gui/gui_actions.py
  tests/taipy/gui/long_runnig/test_long_running.py
Labels: Enhancement, Back-End

#448 Review call_long_callback reference documentation.
  src/taipy/gui/gui_actions.py
Labels: Documentation, Back-End

#452 Root's .gitignore hides doc/extension/demo.py
  doc/extension/.gitignore
  doc/extension/demo.py
Labels: Bug, Delivery

#453 Root's .gitignore hides doc/extension/demo.py
  doc/extension/.gitignore
  doc/extension/demo.py
Labels: Bug, Delivery

#454 Remove backdrop when no onAction (#436)
  gui/src/components/Taipy/Image.spec.tsx
  gui/src/components/Taipy/Image.tsx
  src/taipy/gui/data/utils.py
  src/taipy/gui/version.json
Labels: Bug, Front-End

#439 Support decimator for 3d chart (#440)
  gui/src/components/Taipy/Chart.tsx
  src/taipy/gui/data/decimator/scatter_decimator.py
  src/taipy/gui/data/pandas_data_accessor.py
  src/taipy/gui/data/utils.py
  tests/taipy/gui/gui_specific/test_df_filter.py
Labels: Enhancement, Front-End

#468 Convert CSV file for elements doc to JSON (#460)
  gui/doc/README.md
  gui/doc/active.csv
  gui/doc/button.csv
  gui/doc/chart.csv
  gui/doc/date.csv
  gui/doc/dialog.csv
  gui/doc/expandable.csv
  gui/doc/file_download.csv
  gui/doc/file_selector.csv
  gui/doc/image.csv
  gui/doc/indicator.csv
  gui/doc/input.csv
  gui/doc/layout.csv
  gui/doc/lovComp.csv
  gui/doc/menu.csv
  gui/doc/navbar.csv
  gui/doc/number.csv
  gui/doc/on_change.csv
  gui/doc/pane.csv
  gui/doc/part.csv
  gui/doc/partial.csv
  gui/doc/propagate.csv
  gui/doc/selector.csv
  gui/doc/shared.csv
  gui/doc/sharedInput.csv
  gui/doc/slider.csv
  gui/doc/status.csv
  gui/doc/table.csv
  gui/doc/text.csv
  gui/doc/toggle.csv
  gui/doc/tree.csv
  gui/doc/viselements.json
  gui/package-lock.json
  gui/package.json
Labels: Documentation

#472 Backport to 2.0: Align _GuiSection._from_dict (#469)
  gui/doc/table.csv
  gui/package.json
  gui/packaging/package.json
  gui/src/components/Taipy/AutoLoadingTable.tsx
  gui/src/components/Taipy/Image.spec.tsx
  gui/src/components/Taipy/Image.tsx
  gui/src/components/Taipy/PaginatedTable.tsx
  gui/src/components/Taipy/tableUtils.tsx
  src/taipy/gui/config.py
  src/taipy/gui/renderers/builder.py
  src/taipy/gui/version.json
Labels: Bug, Back-End

#467 Manage editable vs editable[col] (#464)
  gui/doc/table.csv
  gui/src/components/Taipy/AutoLoadingTable.tsx
  gui/src/components/Taipy/Image.tsx
  gui/src/components/Taipy/PaginatedTable.tsx
  gui/src/components/Taipy/tableUtils.tsx
  src/taipy/gui/renderers/builder.py
Labels: Bug, Front-End, Back-End

#470 Align _GuiSection._from_dict (#469)
  gui/doc/table.csv
  gui/doc/viselements.json
  src/taipy/gui/config.py
Labels: Bug, Back-End

#475 'partial' element is not documented.
  gui/doc/viselements.json
Labels: Documentation

#476 'data' property is mandatory in the 'chart' control
  gui/doc/viselements.json
Labels: Documentation

#478 #477 raw text
  gui/doc/viselements.json
  gui/src/components/Taipy/Field.tsx
  gui/src/components/Taipy/utils.ts
  src/taipy/gui/renderers/factory.py
Labels: Enhancement, Front-End, Back-End
