Repository Avaiga/taipy-gui, pull requests merged in 2022-08, with the labels that each got.

#346 on navigate (#332)
  src/taipy/gui/gui.py
Labels: Enhancement, Front-End

#348 on_exception (#347)
  setup.py
  src/taipy/gui/gui.py
Labels: Enhancement, Front-End

#354 #330 adding a UI component in the front WIP
  .github/workflows/test.yml
  .gitignore
  gui/dom/.gitignore
  gui/dom/package-lock.json
  gui/dom/package.json
  gui/dom/src/index.tsx
  gui/dom/tsconfig.json
  gui/package-lock.json
  gui/package.json
  gui/packaging/package.json
  gui/packaging/taipy-gui.d.ts
  gui/postcss.config.js
  gui/public/index.html
  gui/src/components/Taipy/Chart.tsx
  gui/src/components/Taipy/TreeView.spec.tsx
  gui/src/components/Taipy/index.ts
  gui/src/components/pages/TaipyRendered.tsx
  gui/src/extensions/exports.ts
  gui/src/utils/index.ts
  gui/webpack.config.js
  setup.py
  src/taipy/gui/extension/user_element.py
  src/taipy/gui/gui.py
  src/taipy/gui/server.py
  tests/taipy/gui/extension/test_library.py
Labels: Enhancement, Front-End

#343 Fix Gui Stop in Notebook (#320)
  src/taipy/gui/server.py
  src/taipy/gui/utils/__init__.py
  src/taipy/gui/utils/_runtime_manager.py
  src/taipy/gui/utils/singleton.py
Labels: Enhancement, Front-End

#364 #361 extension lov and tabular data support
  .github/workflows/setuptools.yml
  gui/package-lock.json
  gui/packaging/taipy-gui.d.ts
  gui/src/components/Taipy/Chart.tsx
  gui/src/context/taipyReducers.ts
  gui/src/extensions/exports.ts
  src/taipy/gui/extension/user_element.py
  src/taipy/gui/gui.py
  src/taipy/gui/renderers/builder.py
  src/taipy/gui/renderers/factory.py
  tests/taipy/gui/helpers.py
Labels: Enhancement, Front-End

#367 Table and Input
  gui/doc/input.csv
  gui/doc/table.csv
  gui/src/components/Taipy/AutoLoadingTable.spec.tsx
  gui/src/components/Taipy/AutoLoadingTable.tsx
  gui/src/components/Taipy/Input.tsx
  gui/src/components/Taipy/PaginatedTable.spec.tsx
  gui/src/components/Taipy/PaginatedTable.tsx
  gui/src/components/Taipy/TableFilter.tsx
  gui/src/components/Taipy/index.ts
  gui/src/components/Taipy/tableUtils.tsx
  gui/src/components/Taipy/utils.ts
  src/taipy/gui/renderers/builder.py
  src/taipy/gui/renderers/factory.py
Labels: Bug, Enhancement, Front-End

#371 on_action user var name (#368)
  src/taipy/gui/gui.py
  src/taipy/gui/utils/types.py
  tests/taipy/gui/utils/test_types.py
Labels: Bug, Back-End

#374 apache arrow js (#355)
  gui/package-lock.json
  gui/package.json
  gui/src/context/taipyReducers.ts
  gui/src/utils/dataFormat.spec.ts
  gui/src/utils/dataFormat.ts
  gui/tsconfig.json
  src/taipy/gui/data/pandas_data_accessor.py
  src/taipy/gui/gui.py
Labels: Enhancement, Front-End

#378 Cast value on table edit (#365)
  gui/doc/table.csv
  gui/src/components/Taipy/AutoLoadingTable.tsx
  gui/src/components/Taipy/PaginatedTable.tsx
  gui/src/components/Taipy/tableUtils.tsx
  src/taipy/gui/config.py
Labels: Bug, Front-End

#382 #381 block unselect on toggle
  gui/doc/toggle.csv
  gui/src/components/Taipy/ThemeToggle.tsx
  gui/src/components/Taipy/Toggle.spec.tsx
  gui/src/components/Taipy/Toggle.tsx
  src/taipy/gui/renderers/factory.py
  tests/taipy/gui/control/test_toggle.py
Labels: Enhancement, Front-End

#380 slider with dict labels (#379)
  src/taipy/gui/renderers/builder.py
  src/taipy/gui/utils/boolean.py
  tests/taipy/gui/control/test_slider.py
Labels: Bug, Back-End

#373 Feature/update config code
  src/taipy/gui/config.py
Labels: Enhancement, Back-End

#377 fix notebook bug (#362)
  Pipfile
  setup.py
  src/taipy/gui/_default_config.py
  src/taipy/gui/config.py
  src/taipy/gui/gui.py
  src/taipy/gui/server.py
Labels: Bug, Back-End
