Repository Avaiga/taipy-gui, pull requests merged in 2022-04, with the labels that each got.

#209 #198 user input buffer
  gui/src/components/Taipy/Input.spec.tsx
  gui/src/components/Taipy/Input.tsx
Labels: enhancement, Front-End

#212 #210 doc
  gui/doc/active.csv
  gui/doc/button.csv
  gui/doc/button.md
  gui/doc/chart.csv
  gui/doc/chart.md
  gui/doc/date.csv
  gui/doc/dialog.csv
  gui/doc/dialog.md
  gui/doc/expandable.csv
  gui/doc/expandable.md
  gui/doc/file_download.csv
  gui/doc/file_download.md
  gui/doc/file_selector.csv
  gui/doc/file_selector.md
  gui/doc/image.csv
  gui/doc/indicator.csv
  gui/doc/layout.csv
  gui/doc/layout.md
  gui/doc/lovComp.csv
  gui/doc/menu.csv
  gui/doc/menu.md
  gui/doc/navbar.md
  gui/doc/number.csv
  gui/doc/number.md
  gui/doc/on_change.csv
  gui/doc/pane.csv
  gui/doc/pane.md
  gui/doc/partial.csv
  gui/doc/selector.csv
  gui/doc/shared.csv
  gui/doc/slider.csv
  gui/doc/slider.md
  gui/doc/status.csv
  gui/doc/status.md
  gui/doc/table.csv
  gui/doc/table.md
  gui/doc/text.md
  gui/doc/tree.md
  taipy/gui/gui.py
  taipy/gui/partial.py
Labels: documentation, enhancement, Front-End

#213 Control doc typo
  gui/doc/table.csv
Labels: documentation, Front-End

#215 #192 lov type
  gui/doc/tree.md
  taipy/gui/gui.py
  taipy/gui/renderers/builder.py
  taipy/gui/utils/_adapter.py
Labels: bug, Front-End

#220 #217 change delay
  gui/doc/input.csv
  gui/doc/number.csv
  gui/doc/slider.csv
  gui/doc/tree.csv
  gui/src/components/Taipy/Input.tsx
  gui/src/components/Taipy/Slider.tsx
  gui/src/components/Taipy/utils.ts
  taipy/gui/_default_config.py
  taipy/gui/config.py
  taipy/gui/renderers/builder.py
  taipy/gui/renderers/factory.py
Labels: enhancement, Front-End

#223 #197 on_init
  gui/doc/input.csv
  gui/doc/slider.csv
  gui/package-lock.json
  gui/package.json
  taipy/gui/gui.py
  taipy/gui/server.py
Labels: enhancement, Front-End

#225 #199 input on_action
  gui/doc/dialog.csv
  gui/doc/input.csv
  gui/doc/menu.csv
  gui/doc/number.csv
  gui/doc/sharedInput.csv
  gui/src/components/Taipy/Dialog.tsx
  gui/src/components/Taipy/Input.spec.tsx
  gui/src/components/Taipy/Input.tsx
  gui/src/components/Taipy/Menu.tsx
  gui/src/components/Taipy/utils.ts
  taipy/gui/renderers/factory.py
  tests/taipy/gui/control/test_menu.py
Labels: enhancement, Front-End

#222 ssl_context option
  Pipfile
  taipy/gui/gui.py
  taipy/gui/server.py
Labels: enhancement

#224 Update deps
  Pipfile
  setup.py
Labels: Delivery

#228 timezone and class_name (#226 #227)
  gui/src/components/Taipy/tableUtils.tsx
  gui/src/context/taipyReducers.ts
  gui/src/utils/hooks.ts
  gui/src/utils/index.spec.ts
  gui/src/utils/index.ts
  taipy/gui/_default_config.py
  taipy/gui/config.py
  taipy/gui/data/pandas_data_accessor.py
  taipy/gui/gui.py
  taipy/gui/renderers/_html/parser.py
  taipy/gui/renderers/builder.py
  taipy/gui/renderers/utils.py
  taipy/gui/utils/__init__.py
  taipy/gui/utils/getdatecolstrname.py
  tests/taipy/gui/control/test_table.py
  tests/taipy/gui/e2e/renderers/test_markdown_rendering.py
  tests/taipy/gui/gui_specific/test_expression.py
  tests/taipy/gui/server/ws/test_du.py
Labels: bug, Front-End

#229 New release and publish process
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: devops

#237 #236 partial update with empty string
  gui/src/components/pages/TaipyRendered.tsx
Labels: bug, Front-End

#235 #234 check port before starting
  taipy/gui/server.py
Labels: bug, Front-End

#242 fix State ref (#240)
  gui/doc/button.csv
  gui/doc/chart.csv
  gui/doc/dialog.csv
  gui/doc/file_download.csv
  gui/doc/file_selector.csv
  gui/doc/image.csv
  gui/doc/menu.csv
  gui/doc/on_change.csv
  gui/doc/pane.csv
  gui/doc/sharedInput.csv
  gui/doc/table.csv
Labels: bug, documentation, Front-End

#244 fix on_range_change on 1.0 (#240 )
  gui/doc/chart.csv
Labels: bug, documentation, Front-End

#239 support lat lon (#153)
  gui/doc/chart.csv
  gui/src/components/Taipy/Chart.spec.tsx
  gui/src/components/Taipy/Chart.tsx
  taipy/gui/renderers/builder.py
  tests/taipy/gui/control/test_chart.py
  tests/taipy/gui/helpers.py
Labels: enhancement, Front-End

#243 tree selection (#241)
  gui/doc/tree.csv
  gui/src/components/Taipy/TreeView.spec.tsx
  gui/src/components/Taipy/TreeView.tsx
  gui/src/components/Taipy/lovUtils.tsx
  taipy/gui/renderers/factory.py
Labels: enhancement, Front-End

#245 #238 password
  gui/doc/input.csv
  taipy/gui/renderers/builder.py
  taipy/gui/renderers/factory.py
  tests/taipy/gui/control/test_input.py
Labels: enhancement, Front-End

#247 #246 swap lat lon
  gui/doc/chart.csv
  gui/src/components/Taipy/Chart.tsx
  taipy/gui/renderers/builder.py
Labels: bug, Front-End
