Repository Avaiga/taipy-gui, pull requests merged in 2022-05, with the labels that each got.

#252 Fixes in visual elements doc.
  gui/doc/button.csv
  gui/doc/chart.csv
  gui/doc/date.md
  gui/doc/dialog.csv
  gui/doc/expandable.csv
  gui/doc/file_download.csv
  gui/doc/file_selector.csv
  gui/doc/image.csv
  gui/doc/menu.csv
  gui/doc/on_change.csv
  gui/doc/pane.csv
  gui/doc/part.csv
  gui/doc/propagate.csv
  gui/doc/selector.csv
  gui/doc/sharedInput.csv
  gui/doc/slider.csv
  gui/doc/status.csv
  gui/doc/table.csv
  gui/doc/toggle.csv
  taipy/gui/icon.py
Labels: documentation, enhancement

#254 Small fixes in the doc.
  gui/doc/button.csv
  gui/doc/chart.csv
  gui/doc/date.md
  gui/doc/dialog.csv
  gui/doc/expandable.csv
  gui/doc/file_download.csv
  gui/doc/file_selector.csv
  gui/doc/image.csv
  gui/doc/menu.csv
  gui/doc/on_change.csv
  gui/doc/pane.csv
  gui/doc/part.csv
  gui/doc/propagate.csv
  gui/doc/selector.csv
  gui/doc/slider.csv
  gui/doc/status.csv
  gui/doc/table.csv
  gui/doc/toggle.csv
  taipy/gui/icon.py
Labels: documentation, enhancement

#260 fix default css filename (#259)
  taipy/gui/gui.py
Labels: bug, Front-End

#256 Remove DataScopes dependant on flask request (#255)
  taipy/gui/data/data_scope.py
  taipy/gui/gui.py
  taipy/gui/utils/_bindings.py
  tests/taipy/gui/gui_specific/test_variable_binding.py
  tests/taipy/gui/helpers.py
  tests/taipy/gui/utils/test_evaluator.py
Labels: enhancement, Front-End

#258 Prevent the same variable to be evaluated multiple times in on_change function (#257)
  taipy/gui/gui.py
  tests/taipy/gui/e2e/with_action/test_slider_action.py
Labels: enhancement, Front-End

#264 Fix HTTP 308 #263
  gui/src/components/Router.tsx
  gui/src/components/pages/TaipyRendered.tsx
  taipy/gui/gui.py
  taipy/gui/server.py
  tests/taipy/gui/gui_specific/test_multiple_instances.py
  tests/taipy/gui/gui_specific/test_partial.py
  tests/taipy/gui/gui_specific/test_render_route.py
  tests/taipy/gui/gui_specific/test_variable_binding.py
  tests/taipy/gui/helpers.py
  tests/taipy/gui/renderers/test_html_parsing.py
  tests/taipy/gui/server/ws/test_a.py
  tests/taipy/gui/server/ws/test_du.py
  tests/taipy/gui/server/ws/test_on_change.py
  tests/taipy/gui/server/ws/test_ru.py
  tests/taipy/gui/server/ws/test_u.py
  tests/taipy/gui/server/ws/test_with.py
Labels: bug, Front-End

#268 table add only (#267)
  gui/src/components/Taipy/AutoLoadingTable.tsx
  gui/src/components/Taipy/PaginatedTable.tsx
  gui/src/components/Taipy/tableUtils.tsx
Labels: bug, Front-End

#270 marker color and size as column name => multi-value (#269)
  gui/doc/chart.csv
  gui/src/components/Taipy/Chart.tsx
  taipy/gui/renderers/builder.py
  taipy/gui/renderers/utils.py
Labels: enhancement, Front-End

#271 Add max version on dependencies
  setup.py
Labels: devops

#273 Allow for column expression as 1*5 (#84)
  gui/doc/layout.csv
  gui/package-lock.json
  gui/package.json
  gui/src/components/Taipy/Layout.spec.tsx
  gui/src/components/Taipy/Layout.tsx
  setup.py
Labels: enhancement, Front-End

#275 remove doc trigger (#274)
  .github/workflows/doc.yml
Labels: bug, Front-End

#280 indicator width and height + id and classname (#276 #277)
  gui/doc/indicator.csv
  gui/doc/indicator.md
  gui/src/components/Taipy/Indicator.tsx
  taipy/gui/renderers/factory.py
Labels: enhancement, Front-End

#279 manage context id to prepare for serializable callback (#248)
  gui/package-lock.json
  taipy/gui/__init__.py
  taipy/gui/data/data_scope.py
  taipy/gui/gui.py
  taipy/gui/gui_actions.py
  taipy/gui/server.py
  taipy/gui/utils/_bindings.py
  tests/taipy/gui/server/ws/test_with.py
  tests/taipy/gui/utils/test_map_dict.py
Labels: enhancement, Front-End
