Repository Avaiga/taipy-gui, pull requests merged in 2022-11, with the labels that each got.

#479 polar charts (#474)
  gui/doc/viselements.json
  gui/src/components/Taipy/Chart.spec.tsx
  gui/src/components/Taipy/Chart.tsx
  src/taipy/gui/renderers/builder.py
Labels: Enhancement, Front-End, Back-End

#481 #455 do not add an index axys on histogram
  gui/src/components/Taipy/Chart.spec.tsx
  gui/src/components/Taipy/Chart.tsx
  src/taipy/gui/renderers/builder.py
Labels: Bug, Front-End

#482 #386 edit boolean in tables
  gui/src/components/Taipy/AutoLoadingTable.tsx
  gui/src/components/Taipy/PaginatedTable.spec.tsx
  gui/src/components/Taipy/PaginatedTable.tsx
  gui/src/components/Taipy/tableUtils.tsx
Labels: Enhancement, Front-End

#484 Dynamic class name in visual elements (#480)
  gui/doc/viselements.json
  gui/src/components/Taipy/AutoLoadingTable.tsx
  gui/src/components/Taipy/Button.tsx
  gui/src/components/Taipy/Chart.tsx
  gui/src/components/Taipy/DateSelector.tsx
  gui/src/components/Taipy/Dialog.tsx
  gui/src/components/Taipy/Expandable.tsx
  gui/src/components/Taipy/Field.tsx
  gui/src/components/Taipy/FileDownload.tsx
  gui/src/components/Taipy/FileSelector.tsx
  gui/src/components/Taipy/Image.tsx
  gui/src/components/Taipy/Indicator.tsx
  gui/src/components/Taipy/Input.tsx
  gui/src/components/Taipy/Layout.tsx
  gui/src/components/Taipy/Menu.tsx
  gui/src/components/Taipy/MenuCtl.spec.tsx
  gui/src/components/Taipy/MenuCtl.tsx
  gui/src/components/Taipy/NavBar.tsx
  gui/src/components/Taipy/PaginatedTable.tsx
  gui/src/components/Taipy/Pane.tsx
  gui/src/components/Taipy/Part.tsx
  gui/src/components/Taipy/Selector.tsx
  gui/src/components/Taipy/Slider.tsx
  gui/src/components/Taipy/Status.tsx
  gui/src/components/Taipy/StatusList.tsx
  gui/src/components/Taipy/ThemeToggle.tsx
  gui/src/components/Taipy/Toggle.tsx
  gui/src/components/Taipy/TreeView.tsx
  gui/src/components/Taipy/utils.ts
  gui/src/utils/hooks.ts
  gui/src/utils/lov.ts
  src/taipy/gui/gui.py
  src/taipy/gui/renderers/builder.py
  tests/taipy/gui/control/test_indicator.py
  tests/taipy/gui/control/test_menu.py
  tests/taipy/gui/extension/test_library.py
Labels: Enhancement, Front-End

#487 Fix/init file
  pytest.ini
  src/taipy/__init__.py
Labels: Dependencies

#488 do not define font-weight in typography (#486)
  gui/src/components/Taipy/Field.tsx
Labels: Bug, Front-End

#491 number show 0 (#490)
  gui/src/components/Taipy/Input.spec.tsx
  gui/src/components/Taipy/Input.tsx
Labels: Bug, Front-End

#494 fix blocking warnings on release
  .github/workflows/release.yml
  pytest.ini
Labels: Delivery

#495 Update yaml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/setuptools.yml
  .github/workflows/test.yml
  Pipfile
Labels: Enhancement, devops

#499 Protect local files against unwanted access (#498)
  src/taipy/gui/gui.py
  src/taipy/gui/server.py
Labels: Bug, Back-End

#502 taipyignore file (#501)
  Pipfile
  gui/package-lock.json
  gui/package.json
  setup.py
  src/taipy/gui/server.py
  tests/taipy/gui/ignore/no_file/resource.txt
  tests/taipy/gui/ignore/no_file/test_ignore.py
  tests/taipy/gui/ignore/with_file/.taipyignore
  tests/taipy/gui/ignore/with_file/resource.txt
  tests/taipy/gui/ignore/with_file/resource2.txt
  tests/taipy/gui/ignore/with_file/test_with_ignore.py
Labels: Enhancement, 🖰 GUI, Back-End

#504 #503 candlestick chart
  gui/doc/viselements.json
  gui/src/components/Taipy/Chart.spec.tsx
  gui/src/components/Taipy/Chart.tsx
  src/taipy/gui/renderers/builder.py
Labels: 📈 Improvement, Gui: Back-End, GUI: Front-End
