Repository Avaiga/taipy-gui, pull requests merged in 2022-06, with the labels that each got.

#281 #248 serializable callback
  taipy/gui/__init__.py
  taipy/gui/gui.py
  taipy/gui/gui_actions.py
  tests/taipy/gui/actions/test_download.py
  tests/taipy/gui/actions/test_get_context_id.py
  tests/taipy/gui/actions/test_hold_control.py
  tests/taipy/gui/actions/test_invoke_state_callback.py
  tests/taipy/gui/actions/test_navigate.py
  tests/taipy/gui/actions/test_notify.py
  tests/taipy/gui/actions/test_resume_control.py
  tests/taipy/gui/helpers.py
Labels: enhancement, Front-End

#278 gui auth
  taipy/gui/gui.py
  taipy/gui/state.py
  tests/taipy/gui/gui_specific/test_state.py
Labels: enhancement, Front-End, Authorization

#284 Bug/#282 requests are asynchronous
  taipy/gui/data/data_scope.py
  taipy/gui/gui.py
  taipy/gui/server.py
  taipy/gui/state.py
  taipy/gui/utils/_attributes.py
  taipy/gui/utils/_bindings.py
  tests/taipy/gui/actions/test_download.py
  tests/taipy/gui/actions/test_get_context_id.py
  tests/taipy/gui/actions/test_hold_control.py
  tests/taipy/gui/actions/test_invoke_state_callback.py
  tests/taipy/gui/actions/test_navigate.py
  tests/taipy/gui/actions/test_notify.py
  tests/taipy/gui/actions/test_resume_control.py
  tests/taipy/gui/conftest.py
  tests/taipy/gui/control/test_button.py
  tests/taipy/gui/control/test_date.py
  tests/taipy/gui/control/test_file_download.py
  tests/taipy/gui/control/test_file_selector.py
  tests/taipy/gui/control/test_image.py
  tests/taipy/gui/control/test_indicator.py
  tests/taipy/gui/control/test_menu.py
  tests/taipy/gui/control/test_navbar.py
  tests/taipy/gui/control/test_number.py
  tests/taipy/gui/control/test_pane.py
  tests/taipy/gui/control/test_selector.py
  tests/taipy/gui/control/test_slider.py
  tests/taipy/gui/control/test_text.py
  tests/taipy/gui/control/test_toggle.py
  tests/taipy/gui/control/test_tree.py
  tests/taipy/gui/e2e/with_action/test_selector_action.py
  tests/taipy/gui/exception_test/test_exception_bindings.py
  tests/taipy/gui/gui_specific/test_expression.py
  tests/taipy/gui/gui_specific/test_partial.py
  tests/taipy/gui/gui_specific/test_state.py
  tests/taipy/gui/server/http/test_file_upload.py
  tests/taipy/gui/server/ws/test_with.py
  tests/taipy/gui/utils/test_evaluator.py
  tests/taipy/gui/utils/test_map_dict.py
Labels: bug, Front-End

#287 Load taipy enterprise if present
  taipy/__init__.py
Labels: devops

#292 label property for input, number and dropdown selector (#289)
  gui/doc/input.csv
  gui/doc/number.csv
  gui/doc/selector.csv
  gui/package-lock.json
  gui/src/components/Taipy/Input.tsx
  gui/src/components/Taipy/Selector.tsx
  gui/src/components/Taipy/lovUtils.tsx
  gui/src/components/Taipy/utils.ts
  taipy/gui/renderers/factory.py
Labels: enhancement, Front-End

#290 multi level dict access (#288)
  gui/webpack.config.js
  taipy/gui/gui.py
  taipy/gui/server.py
  taipy/gui/utils/_map_dict.py
Labels: bug, Front-End

#293 Change var twice in on_change (#286)
  taipy/gui/gui.py
  tests/taipy/gui/utils/test_evaluator.py
  tests/taipy/gui/utils/test_map_dict.py
Labels: bug, Front-End

#291 Set Pandas version to 1.3
  Pipfile
  setup.py
Labels: Front-End, devops

#250 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
  taipy/gui/server.py
Labels: devops

#303 get module_name through f_globals (#297)
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/setuptools.yml
  .gitignore
  Pipfile
  taipy/gui/utils/get_module_name.py
  tests/taipy/gui/notebook/__init__.py
  tests/taipy/gui/notebook/simple_gui.ipynb
  tests/taipy/gui/notebook/test_notebook_simple_gui.py
  tox.ini
Labels: bug

#305 Additional page scopes fixes (#304)
  taipy/gui/utils/_evaluator.py
  tests/taipy/gui/e2e/with_action/test_slider_input_reload.py
  tests/taipy/gui/helpers.py
  tests/taipy/gui/notebook/simple_gui.ipynb
Labels: bug

#306 Minor refman generation problem.
  taipy/gui/gui.py
Labels: documentation

#316 access module context from state class (#315)
  taipy/gui/__init__.py
  taipy/gui/gui_actions.py
Labels: enhancement, Front-End
