Repository Avaiga/taipy-gui, pull requests merged in 2022-09, with the labels that each got.

#389 Extension doc WiP and logo
  gui/.eslintrc.js
  gui/.gitignore
  gui/package-lock.json
  gui/package.json
  gui/packaging/taipy-gui.d.ts
  gui/public/favicon.ico
  gui/public/favicon.png
  gui/src/components/Taipy/lovUtils.tsx
  gui/src/components/Taipy/tableUtils.tsx
  gui/src/components/Taipy/utils.ts
  gui/src/context/taipyContext.ts
  gui/src/context/taipyReducers.ts
  gui/src/utils/hooks.ts
  gui/src/utils/icon.tsx
  gui/src/utils/lov.ts
  src/taipy/gui/extension/user_element.py
  src/taipy/gui/renderers/builder.py
  src/taipy/gui/types.py
  tests/taipy/gui/actions/test_invoke_state_callback.py
  tests/taipy/gui/control/test_chart.py
  tests/taipy/gui/control/test_dialog.py
  tests/taipy/gui/control/test_input.py
  tests/taipy/gui/control/test_slider.py
  tests/taipy/gui/control/test_status.py
  tests/taipy/gui/control/test_table.py
  tests/taipy/gui/data/test_pandas_data_accessor.py
  tests/taipy/gui/e2e/page_scopes/test_page_scopes_binding_global.py
  tests/taipy/gui/e2e/test_accessor_data_format.py
  tests/taipy/gui/e2e/test_timezone.py
  tests/taipy/gui/e2e/with_action/test_button_action.py
  tests/taipy/gui/e2e/with_action/test_dict.py
  tests/taipy/gui/e2e/with_action/test_selector_action.py
  tests/taipy/gui/e2e/with_action/test_slider_action.py
  tests/taipy/gui/e2e/with_action/test_slider_input_reload.py
  tests/taipy/gui/e2e/with_action/test_text_edit.py
  tests/taipy/gui/extension/test_library.py
  tests/taipy/gui/gui_specific/test_locals_context.py
  tests/taipy/gui/gui_specific/test_render_route.py
  tests/taipy/gui/gui_specific/test_state.py
  tests/taipy/gui/gui_specific/test_variable_binding.py
  tests/taipy/gui/server/http/test_status.py
  tests/taipy/gui/server/ws/test_on_change.py
  tests/taipy/gui/utils/test_evaluator.py
  tests/taipy/gui/utils/test_types.py
Labels: Enhancement, Front-End, Back-End

#393 AttributeError on re evaluation (#392)
  src/taipy/gui/utils/_evaluator.py
  tests/taipy/gui/utils/test_evaluator.py
Labels: Bug, Back-End

#394 Backport: AttributeError on re evaluation (#392)
  taipy/gui/utils/_evaluator.py
  tests/taipy/gui/utils/test_evaluator.py
Labels: Bug, Back-End

#398 Extension: mixed rendering (#397)
  gui/package-lock.json
  gui/package.json
  src/taipy/gui/extension/user_element.py
  src/taipy/gui/gui.py
  src/taipy/gui/renderers/_markdown/postproc.py
  src/taipy/gui/renderers/_markdown/preproc.py
  src/taipy/gui/renderers/builder.py
  src/taipy/gui/renderers/factory.py
  tests/taipy/gui/helpers.py
Labels: Enhancement, Back-End

#390 chart zooming (#384)
  gui/src/components/Taipy/Chart.spec.tsx
  gui/src/components/Taipy/Chart.tsx
  gui/src/context/taipyReducers.ts
  src/taipy/gui/data/decimator/lttb.py
  src/taipy/gui/data/decimator/minmax.py
  src/taipy/gui/data/decimator/rdp.py
  src/taipy/gui/data/pandas_data_accessor.py
  src/taipy/gui/data/utils.py
Labels: Enhancement, Back-End

#404 Remove generated tp_ prefix on on_<action> attribute (#403)
  gui/package-lock.json
  gui/package.json
  gui/packaging/package.json
  gui/packaging/taipy-gui.d.ts
  gui/src/components/Router.tsx
  gui/src/components/Taipy/AutoLoadingTable.tsx
  gui/src/components/Taipy/Button.spec.tsx
  gui/src/components/Taipy/Button.tsx
  gui/src/components/Taipy/Chart.tsx
  gui/src/components/Taipy/DateSelector.tsx
  gui/src/components/Taipy/Dialog.spec.tsx
  gui/src/components/Taipy/Dialog.tsx
  gui/src/components/Taipy/FileDownload.spec.tsx
  gui/src/components/Taipy/FileDownload.tsx
  gui/src/components/Taipy/FileSelector.spec.tsx
  gui/src/components/Taipy/FileSelector.tsx
  gui/src/components/Taipy/Image.spec.tsx
  gui/src/components/Taipy/Image.tsx
  gui/src/components/Taipy/Input.spec.tsx
  gui/src/components/Taipy/Input.tsx
  gui/src/components/Taipy/Menu.spec.tsx
  gui/src/components/Taipy/Menu.tsx
  gui/src/components/Taipy/MenuCtl.spec.tsx
  gui/src/components/Taipy/MenuCtl.tsx
  gui/src/components/Taipy/PaginatedTable.tsx
  gui/src/components/Taipy/Pane.spec.tsx
  gui/src/components/Taipy/Pane.tsx
  gui/src/components/Taipy/Selector.tsx
  gui/src/components/Taipy/Slider.tsx
  gui/src/components/Taipy/Toggle.tsx
  gui/src/components/Taipy/TreeView.tsx
  gui/src/components/Taipy/lovUtils.tsx
  gui/src/components/Taipy/tableUtils.tsx
  gui/src/components/Taipy/utils.ts
  gui/src/components/pages/TaipyRendered.tsx
  gui/src/context/taipyContext.ts
  gui/src/extensions/exports.ts
  gui/src/utils/lov.ts
  src/taipy/gui/extension/user_element.py
  src/taipy/gui/renderers/builder.py
  tests/taipy/gui/control/test_chart.py
  tests/taipy/gui/control/test_dialog.py
  tests/taipy/gui/control/test_file_selector.py
  tests/taipy/gui/control/test_image.py
  tests/taipy/gui/control/test_menu.py
Labels: Enhancement, Front-End, Back-End

#406 #405 user variable name vs var_name
  src/taipy/gui/gui.py
Labels: Bug, Back-End

#409 #408 Gantt like chart
  gui/doc/chart.csv
  gui/package-lock.json
  gui/package.json
  gui/src/components/Taipy/Chart.tsx
  src/taipy/gui/renderers/builder.py
  src/taipy/gui/version.json
Labels: Enhancement, Front-End, Back-End

#402 scatter decimator
  .dockerignore
  gui/src/components/Router.tsx
  gui/src/components/Taipy/Chart.tsx
  src/taipy/gui/data/decimator/__init__.py
  src/taipy/gui/data/decimator/lttb.py
  src/taipy/gui/data/decimator/minmax.py
  src/taipy/gui/data/decimator/rdp.py
  src/taipy/gui/data/decimator/scatter_decimator.py
  src/taipy/gui/data/pandas_data_accessor.py
  src/taipy/gui/data/utils.py
  src/taipy/gui/gui.py
  tests/taipy/gui/conftest.py
  tests/taipy/gui/gui_specific/test_df_filter.py
Labels: Front-End

#411 access locals safely (#410)
  src/taipy/gui/utils/_variable_directory.py
Labels: Bug, Back-End

#413 #412 useDispatch
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/setuptools.yml
  .github/workflows/test.yml
  gui/packaging/taipy-gui.d.ts
  gui/src/extensions/exports.ts
  gui/src/utils/hooks.ts
  tox.ini
Labels: Enhancement, Front-End

#415 Gantt doc
  gui/doc/chart.md
Labels: Documentation, Enhancement

#414 decimator improvement
  gui/src/components/Router.tsx
  gui/src/components/Taipy/Chart.tsx
  src/taipy/gui/data/decimator/lttb.py
  src/taipy/gui/data/decimator/minmax.py
  src/taipy/gui/data/decimator/rdp.py
  src/taipy/gui/data/decimator/scatter_decimator.py
  src/taipy/gui/data/pandas_data_accessor.py
  src/taipy/gui/data/utils.py
  src/taipy/gui/gui.py
Labels: Enhancement, Front-End, Back-End

#418 Refactor code for Extension API doc (#407)
  Pipfile
  gui/src/components/Taipy/index.ts
  gui/src/utils/index.ts
  gui/webpack.config.js
  src/taipy/gui/__init__.py
  src/taipy/gui/data/utils.py
  src/taipy/gui/extension/__init__.py
  src/taipy/gui/extension/library.py
  src/taipy/gui/extension/user_element.py
  src/taipy/gui/gui.py
  src/taipy/gui/gui_actions.py
  src/taipy/gui/renderers/_markdown/postproc.py
  src/taipy/gui/renderers/_markdown/preproc.py
  src/taipy/gui/renderers/builder.py
  src/taipy/gui/renderers/factory.py
  src/taipy/gui/renderers/utils.py
  src/taipy/gui/state.py
  src/taipy/gui/types.py
  tests/taipy/gui/actions/test_get_state_id.py
  tests/taipy/gui/actions/test_invoke_callback.py
  tests/taipy/gui/extension/test_library.py
  tests/taipy/gui/helpers.py
Labels: Documentation, Front-End

#433 unbound Local in Gui.__serve_extension (#432 )
  src/taipy/gui/gui.py
Labels: Bug, Back-End

#434 First version of element library template
  doc/extension/MANIFEST.in
  doc/extension/Pipfile
  doc/extension/README.md
  doc/extension/find_taipy_gui_dir.py
  doc/extension/my_custom_lib/__init__.py
  doc/extension/my_custom_lib/my_library.py
  doc/extension/my_custom_lib/webui/.gitignore
  doc/extension/my_custom_lib/webui/package.json
  doc/extension/my_custom_lib/webui/src/SimpleLabel.tsx
  doc/extension/my_custom_lib/webui/src/index.ts
  doc/extension/my_custom_lib/webui/tsconfig.json
  doc/extension/my_custom_lib/webui/webpack.config.js
  doc/extension/setup.py
Labels: Documentation
